// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4CombZw21_w_TWPPpsaA1Ekw_z1r9iGw',
    appId: '1:1027662199828:web:8285f9f3e8f4f23f683b01',
    messagingSenderId: '1027662199828',
    projectId: 'masar-b9925',
    authDomain: 'masar-b9925.firebaseapp.com',
    storageBucket: 'masar-b9925.firebasestorage.app',
    measurementId: 'G-RF0G3C6NTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxwYfHjUqtiyDk1g6LTAS1xqUeP4U-Wuc',
    appId: '1:1027662199828:android:9c0ed0c806cc5f53683b01',
    messagingSenderId: '1027662199828',
    projectId: 'masar-b9925',
    storageBucket: 'masar-b9925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzW7rUxecKaTC8EDJ5ZcvoErmGiBfKUwg',
    appId: '1:1027662199828:ios:831fa71e6592a7a1683b01',
    messagingSenderId: '1027662199828',
    projectId: 'masar-b9925',
    storageBucket: 'masar-b9925.firebasestorage.app',
    iosClientId: '1027662199828-m67r26hcfpe4ccvpa3sca65uf8n6svs0.apps.googleusercontent.com',
    iosBundleId: 'com.masar.yeStudentTutor',
  );
}
